[Offline search] Ensure the up-to-date database is available in the app
kamatsuoka/goodtags pull request #9
Opened 2024-04-02 19:16 UTC by FuegoFro

This is the second phase in modifying goodtags for ~instant offline search. To recap, at a high level, the cumulative set of changes will look like:
1. Have something that periodically snapshots the canonical barbershoptags.com database into a SQL database suitable for use by the app and host that where the app can download it (https://github.com/kamatsuoka/goodtags/pull/7).
2. Update the app to include the latest (at the time) database when compiling it and fetch the latest database on startup, only downloading it if it's actually newer than what the app already has (**this PR**).
3. Update the app to add a parallel code path to direct searches to the database rather than the API.
4. Once this has been validated, rip out the old code path and solely rely on the local database for searches.

There are two main changes in the PR: ensuring the latest database is downloaded at build time, and downloading the latest database at app startup time.

At build time there's a new `yarn download-search-db` task which pulls the latest DB into the `src/assets/generated_db/` folder. This task is then invoked as a prerequisite for a number of the other `yarn` tasks as well as in the gradle and xcode build configs. This also modifies the Metro config to include the `.sqlite` file as an asset in the bundle.

At app startup time, there's a new utility for transparently ensuring the database is available and kicking off a background update. This code path will copy the database from the app bundle produced by Metro into the app's local storage if there isn't already a database or the one that's already there is older (as determined by the accompanying manifest). It'll then read the remote manifest and, if that's newer, download that database and seamlessly switch out the backing database instance with the new file. That switching out of the existing database is facilitated by the new `DbWrapper` class which tracks live transactions and replaces the underlying database once there are no more transactions; it's effectively a RW lock on the database. All this code relies on promises (which return ~instantly once they're resolved) so the calling code doesn't need to know about any of those details, it just says "give me a database and run this transaction on it".

To test this, I've written some Jest tests for the `DbWrapper` class and have manually tested the in-app update flows:
- No existing local DB -> copy from bundle
- Bundle/app DB newer than local DB -> copy from bundle
- Bundle/app DB older than/same as local DB -> no copy
- Remote DB newer than local DB -> copy from remote
- Remote DB older than/same as local DB -> no copy

Ideally I'd automate these tests with detox but that setup seems to have atrophied and I wasn't able to get it working in a somewhat short amount of time. I may still look into fixing that up (and getting it running in CI) and then automating these tests, but that would be in a subsequent PR.

2024-04-02 19:19 UTC, FuegoFro reviewed
I think there's probably other ways to approach this, I'm certainly open to ideas if you've got any! 😀

2024-04-02 19:19 UTC, FuegoFro commented on ios/goodtags.xcodeproj/project.pbxproj
> +				368F4735A18E08EAEB68A451 /* Download Search DB */,
Note I don't have a macOS machine to run this on, so my changes to this file were fully hand crafted; if you could test this by deleting the `src/assets/generated_db/` directory, running a build from within Xcode, and then verifying that directory is created and populated, I'd be grateful 🙏

2024-04-05 19:07 UTC, FuegoFro commented
Ugh I just found it's not actually unzipping the file when downloading from the remote, gonna have to do a bit more here.

2024-04-06 01:52 UTC, FuegoFro commented
Okay I've done a more thorough test now where I made sure it downloaded the file from the remote and saw that it was able to query against that newly downloaded file.

2024-04-13 21:07 UTC, kamatsuoka requested changes

2024-04-13 21:07 UTC, kamatsuoka commented on scripts/downloadLatestSearchDb.ts
> +  // What an ugly API; If we require Node >= 18 we can just use the new `fetch` API
is there any reason not to require node >= 18?

2024-04-13 21:07 UTC, kamatsuoka commented on scripts/downloadLatestSearchDb.ts
> +  return new Promise((resolve, reject) => {
same question about node 18 / fetch here; or if we can't do that, can we factor out this duplicate code?

2024-04-13 21:07 UTC, kamatsuoka commented on src/modules/sqlUtil.ts
> +  async transactionAsync(
Can we make this sound more like a verb?  `transactAsync`, `runAsyncTransaction`?

2024-04-13 21:07 UTC, kamatsuoka commented on src/modules/sqlUtil.ts
> +// Singleton with our database. Is an array because assigning to a global wasn't updating the value on subsequent usages.
if it's a const it shouldn't be updateable right?

2024-04-13 21:07 UTC, kamatsuoka commented on src/modules/sqlUtil.ts
> +  ).then(/* Ignore, let run in background */)
noticed this "empty then" a couple of times, how is this different from just omitting the then?

2024-04-13 21:07 UTC, kamatsuoka commented on src/modules/sqlUtil.ts
> +  // This is *wild*, the API has no way to write binary content to a file, have to b64 encode it first and write
consider using https://github.com/RonRadtke/react-native-blob-util?tab=readme-ov-file#download-to-storage-directly ?

2024-04-13 23:59 UTC, FuegoFro commented on scripts/downloadLatestSearchDb.ts
> +  // What an ugly API; If we require Node >= 18 we can just use the new `fetch` API
Uhhhhh, I dunno we probably can haha. I think I was just burned by how much work that's been at previous companies, but my guess is we're already using >=18 everywhere (just not requiring it in `packages.json`) 😂 I went ahead and bumped the minimum we require and converted these to the `fetch` API.

2024-04-13 23:59 UTC, FuegoFro commented on src/modules/sqlUtil.ts
> +  async transactionAsync(
I was trying to match the API of the  underlying `SQLiteDatabase` object here, as described by https://docs.expo.dev/versions/latest/sdk/sqlite/#sqlitedatabase, I kinda wanted the wrapper to be somewhat transparent. But given that it doesn't fully act like that object (I'm only forwarding this one method) I'm happy to change the method name!

2024-04-13 23:59 UTC, FuegoFro commented on src/modules/sqlUtil.ts
> +// Singleton with our database. Is an array because assigning to a global wasn't updating the value on subsequent usages.
Originally I'd tried `let dbConnectionPromise = null` but then doing `dbConnectionPromise = ...` didn't update it for subsequent calls. The `const` here means we can't assign to the variable, but whatever value is here still retains its mutability (there's no way to prevent that in JS, which is unfortunate but a discussion for a different time/place haha).

2024-04-13 23:59 UTC, FuegoFro commented on src/modules/sqlUtil.ts
> +  ).then(/* Ignore, let run in background */)
Functionally it's not, it just prevents my IDE from underlining them in yellow and warning me that I have unused promises 😅 Happy to remove them if you'd prefer!

2024-04-13 23:59 UTC, FuegoFro commented on src/modules/sqlUtil.ts
> +  // This is *wild*, the API has no way to write binary content to a file, have to b64 encode it first and write
I just tested it and unfortunately it's not un-gzip'ing the content for us 😕 I do think there's a few ways to handle this:
- Downloaded the gzipped content, install a dep to manually unzip it ourselves
- Install deps that expose streaming fetch and write APIs and transparently unzips it
- Just stick with the in-memory implementation, which is a total of ~7MB of memory while downloading the DB

Honestly I think the last one is probably fine? But happy to look more into other options 👍

2024-04-14 02:30 UTC, kamatsuoka approved these changes

2024-04-14 02:30 UTC, merged